#define MASTER_RIGHT

#define ANALOG_JOYSTICK_X_AXIS_PIN F7
#define ANALOG_JOYSTICK_Y_AXIS_PIN F6
#define POINTING_DEVICE_INVERT_X
#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 1
#define ANALOG_JOYSTICK_SPEED_MAX 4