#define LEFT_JOYSTICK_XPIN F7
#define LEFT_JOYSTICK_YPIN F6
#define RIGHT_JOYSTICK_XPIN F5
#define RIGHT_JOYSTICK_YPIN F4

#define LEFT_DPAD_ROW 4
#define RIGHT_DPAD_ROW 9

#define MOUSE_MODE_NUMBER 1
#define SCROLL_MODE_NUMBER 2
#define DPAD_MODE_NUMBER 3
#define FUSION_MODE_NUMBER 4

// #define UP_NUMBER 2
// #define LEFT_NUMBER 3
// #define RIGHT_NUMBER 5
// #define DOWN_NUMBER 7
#define SAME_WAY_NUMBER 11
#define OPPOSITE_WAY_NUMBER 13
#define MOUSE_ONLY_NUMBER 17
#define FUSION_ONLY_NUMBER 19

#define MOUSE_DEADZONE 50
#define SCROLL_DEADZONE 50
#define DPAD_DEADZONE 150

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 4
// #define AUTO_MOUSE_TIME 1000