#define JOYSTICK_XPIN F7
#define JOYSTICK_YPIN F6

#define DPAD_ROW 4

#define MOUSE_MODE_NUMBER 1
#define SCROLL_MODE_NUMBER 2
#define DPAD_MODE_NUMBER 3

#define MOUSE_DEADZONE 50
#define SCROLL_DEADZONE 50
#define DPAD_DEADZONE 150

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 4